### PR TITLE
Longest bitonic sequence

### PR DESCRIPTION
**Pull request by pratik0316**
[Longest bitonic sequence ](https://www.geeksforgeeks.org/longest-bitonic-subsequence-dp-15/)

### CODE REVIEW

**Comment by pratik0316** [comment]
@skm2000 bitonic ta.

**Comment by bisakhmondal** [comment]
Wah!! vai ab toh kuch jadai ho rha hai!!😂

**Comment by pratik0316** [comment]
hocchilo na bollo tai ...

**Comment by bisakhmondal** [comment]
Are nah nah just kidding. Darun initiative

**Pull request merged**
